### ISSUE TITLE
Favicon image isn't loading

### ISSUE THREAD

**Issue by eddieharrison** [aphtoken/aph-desktop-web-dex#4]
https://dex.aphelion.org/static/aphelion_favicon.png isn't being fulfilled by the server. I thought this would be included in the build and accessible as the other built files are. Maybe an issue with the server handling?

**Comment by jsolman** [comment]
It was an issue with the deployment. All the other artifacts are in subdirectories except for that one, and it didn't get deployed. It has been deployed now.
